"""Global application constants for HANDVO."""

# Hand Landmark Indices (MediaPipe 21 Hand Landmarks)
WRIST = 0
THUMB_CMC = 1
THUMB_MCP = 2
THUMB_IP = 3
THUMB_TIP = 4

INDEX_MCP = 5
INDEX_PIP = 6
INDEX_DIP = 7
INDEX_TIP = 8

MIDDLE_MCP = 9
MIDDLE_PIP = 10
MIDDLE_DIP = 11
MIDDLE_TIP = 12

RING_MCP = 13
RING_PIP = 14
RING_DIP = 15
RING_TIP = 16

PINKY_MCP = 17
PINKY_PIP = 18
PINKY_DIP = 19
PINKY_TIP = 20

# Interaction & Timing Defaults
DEFAULT_DWELL_TIME_SEC = 0.80
DEFAULT_COOLDOWN_SEC = 0.60
DEFAULT_PINCH_THRESHOLD = 0.05

# Window Dimensions
DEFAULT_WINDOW_WIDTH = 1024
DEFAULT_WINDOW_HEIGHT = 720
MIN_WINDOW_WIDTH = 880
MIN_WINDOW_HEIGHT = 620
